import type { EquationTemplate } from "@/types/equationTemplates";

/**
 * Predefined equation templates organized by category
 */
export const equationTemplates: EquationTemplate[] = [
  // Algebra
  {
    id: "poly-quadratic",
    name: "Quadratic Polynomial",
    description: "Standard quadratic equation ax² + bx + c",
    category: "algebra",
    tags: ["polynomial"],
    expression: "a*x^2 + b*x + c",
    latex: "ax^{2} + bx + c",
    mode: "2d",
    variables: {
      a: { default: 1, description: "Coefficient of x²" },
      b: { default: 0, description: "Coefficient of x" },
      c: { default: 0, description: "Constant term" },
    },
    examples: ["x^2", "x^2 + 2*x + 1", "2*x^2 - 5*x + 3"],
  },
  {
    id: "poly-cubic",
    name: "Cubic Polynomial",
    description: "Cubic equation ax³ + bx² + cx + d",
    category: "algebra",
    tags: ["polynomial"],
    expression: "a*x^3 + b*x^2 + c*x + d",
    latex: "ax^{3} + bx^{2} + cx + d",
    mode: "2d",
    variables: {
      a: { default: 1, description: "Coefficient of x³" },
      b: { default: 0, description: "Coefficient of x²" },
      c: { default: 0, description: "Coefficient of x" },
      d: { default: 0, description: "Constant term" },
    },
  },
  {
    id: "rational",
    name: "Rational Function",
    description: "Ratio of two polynomials",
    category: "algebra",
    tags: ["rational"],
    expression: "(a*x + b) / (c*x + d)",
    latex: "\\frac{ax + b}{cx + d}",
    mode: "2d",
    variables: {
      a: { default: 1, description: "Numerator coefficient" },
      b: { default: 0, description: "Numerator constant" },
      c: { default: 1, description: "Denominator coefficient" },
      d: { default: 1, description: "Denominator constant" },
    },
    notes: "Watch for vertical asymptotes where denominator equals zero",
  },

  // Trigonometry
  {
    id: "sin-basic",
    name: "Sine Wave",
    description: "Basic sine function with amplitude and frequency",
    category: "trigonometry",
    tags: ["trigonometric", "wave"],
    expression: "A*sin(B*x + C)",
    latex: "A\\sin(Bx + C)",
    mode: "2d",
    variables: {
      A: { default: 1, description: "Amplitude" },
      B: { default: 1, description: "Frequency" },
      C: { default: 0, description: "Phase shift" },
    },
    examples: ["sin(x)", "2*sin(x)", "sin(2*x)", "sin(x + pi/2)"],
  },
  {
    id: "cos-basic",
    name: "Cosine Wave",
    description: "Basic cosine function",
    category: "trigonometry",
    tags: ["trigonometric", "wave"],
    expression: "A*cos(B*x + C)",
    latex: "A\\cos(Bx + C)",
    mode: "2d",
    variables: {
      A: { default: 1, description: "Amplitude" },
      B: { default: 1, description: "Frequency" },
      C: { default: 0, description: "Phase shift" },
    },
  },
  {
    id: "tan-basic",
    name: "Tangent Function",
    description: "Basic tangent function",
    category: "trigonometry",
    tags: ["trigonometric"],
    expression: "A*tan(B*x + C)",
    latex: "A\\tan(Bx + C)",
    mode: "2d",
    variables: {
      A: { default: 1, description: "Amplitude" },
      B: { default: 1, description: "Frequency" },
      C: { default: 0, description: "Phase shift" },
    },
    notes: "Has vertical asymptotes at odd multiples of π/2",
  },
  {
    id: "sin-cos-combined",
    name: "Combined Sine and Cosine",
    description: "Sum of sine and cosine waves",
    category: "trigonometry",
    tags: ["trigonometric", "wave"],
    expression: "A*sin(x) + B*cos(x)",
    latex: "A\\sin(x) + B\\cos(x)",
    mode: "2d",
    variables: {
      A: { default: 1, description: "Sine amplitude" },
      B: { default: 1, description: "Cosine amplitude" },
    },
  },

  // Calculus
  {
    id: "derivative-poly",
    name: "Derivative of Polynomial",
    description: "First derivative of a polynomial",
    category: "calculus",
    tags: ["differential", "polynomial"],
    expression: "d/dx (a*x^3 + b*x^2 + c*x + d)",
    latex: "\\frac{d}{dx}(ax^{3} + bx^{2} + cx + d)",
    mode: "2d",
    variables: {
      a: { default: 1, description: "Coefficient of x³" },
      b: { default: 1, description: "Coefficient of x²" },
      c: { default: 1, description: "Coefficient of x" },
      d: { default: 0, description: "Constant" },
    },
  },
  {
    id: "integral-poly",
    name: "Integral of Polynomial",
    description: "Indefinite integral of a polynomial",
    category: "calculus",
    tags: ["integral", "polynomial"],
    expression: "int (a*x^2 + b*x + c) dx",
    latex: "\\int (ax^{2} + bx + c) dx",
    mode: "2d",
    variables: {
      a: { default: 1, description: "Coefficient of x²" },
      b: { default: 1, description: "Coefficient of x" },
      c: { default: 0, description: "Constant" },
    },
  },
  {
    id: "definite-integral",
    name: "Definite Integral",
    description: "Definite integral with bounds",
    category: "calculus",
    tags: ["integral"],
    expression: "int_0^1 (x^2) dx",
    latex: "\\int_{0}^{1} x^{2} dx",
    mode: "2d",
    notes: "Evaluates the area under the curve from 0 to 1",
  },

  // Differential Equations
  {
    id: "ode-first-order",
    name: "First Order ODE",
    description: "dy/dx = f(x,y)",
    category: "differential-equations",
    tags: ["differential"],
    expression: "d/dx y = x*y",
    latex: "\\frac{dy}{dx} = xy",
    mode: "2d",
    notes: "First order ordinary differential equation",
  },
  {
    id: "ode-second-order",
    name: "Second Order ODE",
    description: "d²y/dx² = f(x,y,dy/dx)",
    category: "differential-equations",
    tags: ["differential"],
    expression: "d/dx d/dx y = -y",
    latex: "\\frac{d^{2}y}{dx^{2}} = -y",
    mode: "2d",
    notes: "Second order ordinary differential equation (harmonic oscillator)",
  },

  // Physics
  {
    id: "projectile-motion-x",
    name: "Projectile Motion (Horizontal)",
    description: "Horizontal position of projectile: x = v₀t",
    category: "physics",
    tags: ["motion", "parametric"],
    expression: "v0*t",
    latex: "v_{0}t",
    mode: "parametric",
    variables: {
      v0: { default: 10, description: "Initial horizontal velocity" },
    },
  },
  {
    id: "projectile-motion-y",
    name: "Projectile Motion (Vertical)",
    description: "Vertical position: y = v₀t - ½gt²",
    category: "physics",
    tags: ["motion", "parametric"],
    expression: "v0*t - 0.5*g*t^2",
    latex: "v_{0}t - \\frac{1}{2}gt^{2}",
    mode: "parametric",
    variables: {
      v0: { default: 20, description: "Initial vertical velocity" },
      g: { default: 9.8, description: "Gravitational acceleration" },
    },
  },
  {
    id: "simple-harmonic",
    name: "Simple Harmonic Motion",
    description: "x(t) = A cos(ωt + φ)",
    category: "physics",
    tags: ["motion", "wave", "trigonometric"],
    expression: "A*cos(omega*t + phi)",
    latex: "A\\cos(\\omega t + \\phi)",
    mode: "2d",
    variables: {
      A: { default: 1, description: "Amplitude" },
      omega: { default: 1, description: "Angular frequency" },
      phi: { default: 0, description: "Phase constant" },
    },
  },
  {
    id: "wave-equation",
    name: "Wave Equation",
    description: "Traveling wave: y = A sin(kx - ωt)",
    category: "physics",
    tags: ["wave", "trigonometric"],
    expression: "A*sin(k*x - omega*t)",
    latex: "A\\sin(kx - \\omega t)",
    mode: "2d",
    variables: {
      A: { default: 1, description: "Amplitude" },
      k: { default: 1, description: "Wave number" },
      omega: { default: 1, description: "Angular frequency" },
    },
  },

  // Parametric Forms
  {
    id: "circle-parametric",
    name: "Circle (Parametric)",
    description: "Parametric form of a circle: x = r cos(t), y = r sin(t)",
    category: "parametric",
    tags: ["parametric", "geometry"],
    expression: "x = r*cos(t), y = r*sin(t)",
    latex: "x = r\\cos(t),\\, y = r\\sin(t)",
    mode: "parametric",
    variables: {
      r: { default: 1, description: "Radius" },
    },
    examples: ["x = cos(t), y = sin(t)", "x = 2*cos(t), y = 2*sin(t)"],
  },
  {
    id: "ellipse-parametric",
    name: "Ellipse (Parametric)",
    description: "Parametric form of an ellipse",
    category: "parametric",
    tags: ["parametric", "geometry"],
    expression: "x = a*cos(t), y = b*sin(t)",
    latex: "x = a\\cos(t),\\, y = b\\sin(t)",
    mode: "parametric",
    variables: {
      a: { default: 2, description: "Semi-major axis" },
      b: { default: 1, description: "Semi-minor axis" },
    },
  },
  {
    id: "cycloid",
    name: "Cycloid",
    description: "Path traced by a point on a rolling circle",
    category: "parametric",
    tags: ["parametric", "geometry"],
    expression: "x = r*(t - sin(t)), y = r*(1 - cos(t))",
    latex: "x = r(t - \\sin(t)),\\, y = r(1 - \\cos(t))",
    mode: "parametric",
    variables: {
      r: { default: 1, description: "Radius of rolling circle" },
    },
  },
  {
    id: "spiral",
    name: "Archimedean Spiral",
    description: "Spiral with constant separation",
    category: "parametric",
    tags: ["parametric", "polar"],
    expression: "x = a*t*cos(t), y = a*t*sin(t)",
    latex: "x = at\\cos(t),\\, y = at\\sin(t)",
    mode: "parametric",
    variables: {
      a: { default: 1, description: "Spiral constant" },
    },
  },

  // Polar Forms
  {
    id: "circle-polar",
    name: "Circle (Polar)",
    description: "Circle in polar coordinates: r = a",
    category: "polar",
    tags: ["polar", "geometry"],
    expression: "r = a",
    latex: "r = a",
    mode: "polar",
    variables: {
      a: { default: 1, description: "Radius" },
    },
  },
  {
    id: "rose-curve",
    name: "Rose Curve",
    description: "Polar rose: r = a cos(nθ)",
    category: "polar",
    tags: ["polar", "geometry"],
    expression: "r = a*cos(n*theta)",
    latex: "r = a\\cos(n\\theta)",
    mode: "polar",
    variables: {
      a: { default: 1, description: "Amplitude" },
      n: { default: 3, description: "Number of petals" },
    },
  },
  {
    id: "cardioid",
    name: "Cardioid",
    description: "Heart-shaped curve: r = a(1 + cos(θ))",
    category: "polar",
    tags: ["polar", "geometry"],
    expression: "r = a*(1 + cos(theta))",
    latex: "r = a(1 + \\cos(\\theta))",
    mode: "polar",
    variables: {
      a: { default: 1, description: "Scale factor" },
    },
  },
  {
    id: "lemniscate",
    name: "Lemniscate of Bernoulli",
    description: "Figure-eight curve: r² = a² cos(2θ)",
    category: "polar",
    tags: ["polar", "geometry"],
    expression: "r = a*sqrt(cos(2*theta))",
    latex: "r = a\\sqrt{\\cos(2\\theta)}",
    mode: "polar",
    variables: {
      a: { default: 1, description: "Scale factor" },
    },
  },

  // Implicit Forms
  {
    id: "circle-implicit",
    name: "Circle (Implicit)",
    description: "Implicit form: x² + y² = r²",
    category: "implicit",
    tags: ["implicit", "geometry"],
    expression: "x^2 + y^2 = r^2",
    latex: "x^{2} + y^{2} = r^{2}",
    mode: "implicit",
    variables: {
      r: { default: 1, description: "Radius" },
    },
  },
  {
    id: "ellipse-implicit",
    name: "Ellipse (Implicit)",
    description: "Implicit form: x²/a² + y²/b² = 1",
    category: "implicit",
    tags: ["implicit", "geometry"],
    expression: "x^2/a^2 + y^2/b^2 = 1",
    latex: "\\frac{x^{2}}{a^{2}} + \\frac{y^{2}}{b^{2}} = 1",
    mode: "implicit",
    variables: {
      a: { default: 2, description: "Semi-major axis" },
      b: { default: 1, description: "Semi-minor axis" },
    },
  },
  {
    id: "hyperbola",
    name: "Hyperbola",
    description: "Implicit form: x²/a² - y²/b² = 1",
    category: "implicit",
    tags: ["implicit", "geometry"],
    expression: "x^2/a^2 - y^2/b^2 = 1",
    latex: "\\frac{x^{2}}{a^{2}} - \\frac{y^{2}}{b^{2}} = 1",
    mode: "implicit",
    variables: {
      a: { default: 1, description: "Semi-major axis" },
      b: { default: 1, description: "Semi-minor axis" },
    },
  },

  // Series
  {
    id: "fourier-sine",
    name: "Fourier Sine Series",
    description: "Fourier series with sine terms",
    category: "series",
    tags: ["series", "fourier", "trigonometric"],
    expression: "sum_{n=1}^N (a_n*sin(n*x))",
    latex: "\\sum_{n=1}^{N} a_{n}\\sin(nx)",
    mode: "2d",
    variables: {
      N: { default: 5, description: "Number of terms", min: 1, max: 20 },
    },
    notes: "Approximate periodic functions using sine waves",
  },
  {
    id: "taylor-exp",
    name: "Taylor Series for eˣ",
    description: "Taylor expansion of exponential function",
    category: "series",
    tags: ["series", "exponential"],
    expression: "sum_{n=0}^N (x^n / n!)",
    latex: "\\sum_{n=0}^{N} \\frac{x^{n}}{n!}",
    mode: "2d",
    variables: {
      N: { default: 10, description: "Number of terms", min: 1, max: 20 },
    },
  },
  {
    id: "taylor-sin",
    name: "Taylor Series for sin(x)",
    description: "Taylor expansion of sine function",
    category: "series",
    tags: ["series", "trigonometric"],
    expression: "sum_{n=0}^N ((-1)^n * x^(2*n+1) / (2*n+1)!)",
    latex: "\\sum_{n=0}^{N} \\frac{(-1)^{n}x^{2n+1}}{(2n+1)!}",
    mode: "2d",
    variables: {
      N: { default: 5, description: "Number of terms", min: 1, max: 15 },
    },
  },
];

